name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-job-list
          npm run fetch
          npm run gen-index
          git status --porcelain

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          PRESERVE: true
          GIT_CONFIG_NAME: dailyrandomphoto-bot
          GIT_CONFIG_EMAIL: dailyrandomphoto@example.com
          # BASE_BRANCH: master
          # COMMIT_MESSAGE: Deploying to master from ${{ github.repository }} @ master @ https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          # SINGLE_COMMIT: true
